In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [23]:
# data = pd.read_csv('y_total_with_runs.csv')

In [246]:
sub = pd.read_csv('submission.csv')
hybrid = pd.read_csv('Hybrid_Classified.csv')

sub = sub.rename(columns = {'surface':'surfacesub'})
hybrid = hybrid.rename(columns = {'surface':'surfacehybrid'})

print ("Submission data is ready")

Submission data is ready

In [249]:
subtest = pd.concat([sub['series_id'], sub['surfacesub'], hybrid['surfacehybrid']], axis=1)
subtest

   series_id  surfacesub           surfacehybrid
0          0       tiled  hard_tiles_large_space
1          1        wood                concrete
2          2       tiled                   tiled
3          3      carpet                  carpet
4          4  soft_tiles              soft_tiles

In [254]:
subtest

      series_id              surfacesub           surfacehybrid
0             0                   tiled  hard_tiles_large_space
1             1                    wood                concrete
2             2                   tiled                   tiled
3             3                  carpet                  carpet
4             4              soft_tiles              soft_tiles
5             5                concrete                concrete
6             6                soft_pvc                soft_pvc
7             7  hard_tiles_large_space  hard_tiles_large_space
8             8                    wood                    wood
9             9                    wood                soft_pvc
10           10                soft_pvc                   tiled
11           11                   tiled                    wood
12           12                    wood              soft_tiles
13           13              soft_tiles                    wood
14           14           fine_concrete                  carpet
15           15                    wood           fine_concrete
16           16                concrete           fine_concrete
17           17              soft_tiles                    wood
18           18                concrete                soft_pvc
19           19           fine_concrete                soft_pvc
20           20                    wood  hard_tiles_large_space
21           21                    wood                concrete
22           22                soft_pvc                    wood
23           23  hard_tiles_large_space                concrete
24           24                concrete                   tiled
25           25                    wood                soft_pvc
26           26                concrete              hard_tiles
27           27                   tiled                soft_pvc
28           28                    wood                soft_pvc
29           29                   tiled              hard_tiles
...         ...                     ...                     ...
3786       3786                   tiled                   tiled
3787       3787                concrete                soft_pvc
3788       3788                concrete                    wood
3789       3789           fine_concrete  hard_tiles_large_space
3790       3790  hard_tiles_large_space                    wood
3791       3791                concrete              soft_tiles
3792       3792                soft_pvc                    wood
3793       3793           fine_concrete                   tiled
3794       3794                concrete  hard_tiles_large_space
3795       3795           fine_concrete                   tiled
3796       3796  hard_tiles_large_space              soft_tiles
3797       3797                concrete                soft_pvc
3798       3798                    wood  hard_tiles_large_space
3799       3799                concrete                soft_pvc
3800       3800              soft_tiles                    wood
3801       3801                    wood                soft_pvc
3802       3802                soft_pvc  hard_tiles_large_space
3803       3803                concrete                    wood
3804       3804                    wood              soft_tiles
3805       3805                    wood                concrete
3806       3806                concrete                   tiled
3807       3807                soft_pvc                concrete
3808       3808                   tiled                soft_pvc
3809       3809                soft_pvc              soft_tiles
3810       3810                soft_pvc              soft_tiles
3811       3811                soft_pvc                   tiled
3812       3812                  carpet                    wood
3813       3813                concrete                concrete
3814       3814                    wood                soft_pvc
3815       3815                    wood                soft_pvc

[3816 rows x 3 columns]

In [250]:
differents = []
for i in range (0,subtest.shape[0]): 
    labels = list(subtest.iloc[i,1:])
    result = len(set(labels))>1
    if result:
        differents.append((i, str(labels)))
        
differents = pd.DataFrame(differents, columns=['idx','group']) 
differents.head()

   idx                                group
0    0  ['tiled', 'hard_tiles_large_space']
1    1                 ['wood', 'concrete']
2    9                 ['wood', 'soft_pvc']
3   10                ['soft_pvc', 'tiled']
4   11                    ['tiled', 'wood']

In [259]:
differents['count'].sum()

3297

In [251]:
differents['group'].nunique()

66

In [252]:
differents['count'] = differents.groupby('group')['group'].transform('count')
differents = differents.sort_values(by=['count'], ascending=False)
differents = differents.drop(['idx'],axis=1)
differents = differents.drop_duplicates()

In [253]:
differents.head(10)

                              group  count
1648       ['concrete', 'soft_pvc']    157
1156       ['soft_pvc', 'concrete']    131
714            ['wood', 'soft_pvc']    128
1279           ['concrete', 'wood']    111
2128           ['soft_pvc', 'wood']     93
673            ['wood', 'concrete']     91
503   ['fine_concrete', 'soft_pvc']     90
1265  ['concrete', 'fine_concrete']     87
3217     ['soft_tiles', 'soft_pvc']     83
2339     ['soft_pvc', 'soft_tiles']     83

In [210]:
# x = 0
# groups = []

# for group in data['run_id']:
#     groups.append(data[data['run_id']==x])
#     x += 1

len(groups[151])

26

In [244]:
groups[106]

      series_id surface  run_id  run_pos
4868       4868   empty     106        1
5110       5110   empty     106        0
5771       5771   empty     106        4
6089       6089   empty     106        3
7074       7074   empty     106        2

In [236]:
groups[99]['surface'] = 'concrete'

c:\users\doomb\anaconda3\envs\capstone2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [219]:
groups[87]['surface'] = 'soft_tiles'

c:\users\doomb\anaconda3\envs\capstone2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [216]:
groups[86]['surface'] = 'carpet'

c:\users\doomb\anaconda3\envs\capstone2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [ ]:
groups[5]['surface'] = 'hard_tiles'

In [184]:
groups[78]['surface'] = 'hard_tiles_large_space'

c:\users\doomb\anaconda3\envs\capstone2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [178]:
groups[76]['surface'] = 'soft_pvc'

c:\users\doomb\anaconda3\envs\capstone2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [239]:
groups[101]['surface'] = 'fine_concrete'

c:\users\doomb\anaconda3\envs\capstone2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [181]:
groups[77]['surface'] = 'wood'

c:\users\doomb\anaconda3\envs\capstone2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [224]:
groups[89]['surface'] = 'tiled'

c:\users\doomb\anaconda3\envs\capstone2\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [ ]:
x = 0
groups = []

for group in data['run_id']:
    groups.append(data[data['run_id']==x])
    x += 1

In [22]:
data

      series_id        surface  run_id  run_pos
0             0  fine_concrete     101      159
1             1  fine_concrete      24       14
2             2  fine_concrete       5        4
3             3  fine_concrete      24       42
4             4  fine_concrete      87      164
5             5  fine_concrete     148      128
6             6  fine_concrete      18       26
7             7  fine_concrete      24       49
8             8  fine_concrete       6       13
9             9  fine_concrete     148       93
10           10  fine_concrete      11      149
11           11  fine_concrete     148      136
12           12  fine_concrete     141       25
13           13  fine_concrete     141       29
14           14  fine_concrete      96      116
15           15  fine_concrete     136       56
16           16  fine_concrete     136       76
17           17  fine_concrete      22       43
18           18  fine_concrete      21       75
19           19  fine_concrete       0        0
20           20  fine_concrete     148       90
21           21  fine_concrete       6        5
22           22  fine_concrete      87      192
23           23  fine_concrete      21       23
24           24  fine_concrete       0       25
25           25  fine_concrete      87       40
26           26  fine_concrete     101      167
27           27  fine_concrete     118      111
28           28  fine_concrete     148       81
29           29  fine_concrete       6       15
...         ...            ...     ...      ...
7596       7596  fine_concrete     148        0
7597       7597  fine_concrete     139       43
7598       7598  fine_concrete     149        0
7599       7599  fine_concrete     128       18
7600       7600  fine_concrete     143        5
7601       7601  fine_concrete     150        0
7602       7602  fine_concrete     118       44
7603       7603  fine_concrete     101      127
7604       7604  fine_concrete      96       14
7605       7605  fine_concrete      31      135
7606       7606  fine_concrete     147       17
7607       7607  fine_concrete      96       58
7608       7608  fine_concrete      68       11
7609       7609  fine_concrete      42       24
7610       7610  fine_concrete      87       10
7611       7611  fine_concrete      56       21
7612       7612  fine_concrete     118       77
7613       7613  fine_concrete      88        1
7614       7614  fine_concrete      96       88
7615       7615  fine_concrete      75       32
7616       7616  fine_concrete       8       17
7617       7617  fine_concrete     145       33
7618       7618  fine_concrete      36      142
7619       7619  fine_concrete     119       72
7620       7620  fine_concrete     108       91
7621       7621  fine_concrete      16       19
7622       7622  fine_concrete      31       34
7623       7623  fine_concrete     149        3
7624       7624  fine_concrete      24       65
7625       7625  fine_concrete      61       28

[7626 rows x 4 columns]

In [13]:
data['surface'][0]

'fine_concrete'

In [12]:
data[data['run_id']==0]['surface']

19      soft_tiles
24      soft_tiles
30      soft_tiles
31      soft_tiles
52      soft_tiles
80      soft_tiles
88      soft_tiles
106     soft_tiles
114     soft_tiles
129     soft_tiles
135     soft_tiles
136     soft_tiles
137     soft_tiles
140     soft_tiles
150     soft_tiles
240     soft_tiles
253     soft_tiles
258     soft_tiles
291     soft_tiles
293     soft_tiles
298     soft_tiles
307     soft_tiles
321     soft_tiles
348     soft_tiles
370     soft_tiles
372     soft_tiles
406     soft_tiles
440     soft_tiles
445     soft_tiles
452     soft_tiles
           ...
6646         empty
6693         empty
6706         empty
6775         empty
6818         empty
6867         empty
6886         empty
6890         empty
6894         empty
6923         empty
6961         empty
7035         empty
7037         empty
7041         empty
7045         empty
7060         empty
7136         empty
7178         empty
7207         empty
7250         empty
7359         empty
7364         empty
7375         empty
7378         empty
7398         empty
7445         empty
7516         empty
7538         empty
7539         empty
7584         empty
Name: surface, Length: 227, dtype: object

In [11]:
data['surface']

0                fine_concrete
1                     concrete
2                     concrete
3                     concrete
4                   soft_tiles
5                        tiled
6                     soft_pvc
7                     concrete
8       hard_tiles_large_space
9                        tiled
10                    soft_pvc
11                       tiled
12                      carpet
13                      carpet
14                    concrete
15                      carpet
16                      carpet
17                  soft_tiles
18                       tiled
19                  soft_tiles
20                       tiled
21      hard_tiles_large_space
22                  soft_tiles
23                       tiled
24                  soft_tiles
25                  soft_tiles
26               fine_concrete
27                  hard_tiles
28                       tiled
29      hard_tiles_large_space
                 ...
7596                     empty
7597                     empty
7598                     empty
7599                     empty
7600                     empty
7601                     empty
7602                     empty
7603                     empty
7604                     empty
7605                     empty
7606                     empty
7607                     empty
7608                     empty
7609                     empty
7610                     empty
7611                     empty
7612                     empty
7613                     empty
7614                     empty
7615                     empty
7616                     empty
7617                     empty
7618                     empty
7619                     empty
7620                     empty
7621                     empty
7622                     empty
7623                     empty
7624                     empty
7625                     empty
Name: surface, Length: 7626, dtype: object

In [8]:
data[data['run_id']==0]

      series_id     surface  run_id  run_pos
19           19  soft_tiles       0        0
24           24  soft_tiles       0       25
30           30  soft_tiles       0       19
31           31  soft_tiles       0       43
52           52  soft_tiles       0       26
80           80  soft_tiles       0       17
88           88  soft_tiles       0        6
106         106  soft_tiles       0       83
114         114  soft_tiles       0       61
129         129  soft_tiles       0       49
135         135  soft_tiles       0       48
136         136  soft_tiles       0       78
137         137  soft_tiles       0       10
140         140  soft_tiles       0       92
150         150  soft_tiles       0       13
240         240  soft_tiles       0       84
253         253  soft_tiles       0       15
258         258  soft_tiles       0       96
291         291  soft_tiles       0       80
293         293  soft_tiles       0       34
298         298  soft_tiles       0       65
307         307  soft_tiles       0       73
321         321  soft_tiles       0       45
348         348  soft_tiles       0       77
370         370  soft_tiles       0       24
372         372  soft_tiles       0       11
406         406  soft_tiles       0       54
440         440  soft_tiles       0       36
445         445  soft_tiles       0       23
452         452  soft_tiles       0        3
...         ...         ...     ...      ...
6646       6646       empty       0      110
6693       6693       empty       0      174
6706       6706       empty       0      211
6775       6775       empty       0      156
6818       6818       empty       0      103
6867       6867       empty       0      159
6886       6886       empty       0      216
6890       6890       empty       0      182
6894       6894       empty       0      133
6923       6923       empty       0      199
6961       6961       empty       0      149
7035       7035       empty       0      141
7037       7037       empty       0      107
7041       7041       empty       0      109
7045       7045       empty       0      137
7060       7060       empty       0      116
7136       7136       empty       0      198
7178       7178       empty       0      108
7207       7207       empty       0      226
7250       7250       empty       0      183
7359       7359       empty       0      147
7364       7364       empty       0      223
7375       7375       empty       0      150
7378       7378       empty       0      148
7398       7398       empty       0      210
7445       7445       empty       0      189
7516       7516       empty       0      202
7538       7538       empty       0      175
7539       7539       empty       0      117
7584       7584       empty       0      191

[227 rows x 4 columns]